server:
  port: 8030
spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
#  注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
    instance:
      prefer-ip-address: true


